[package]
name = "ffi_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = "0.13.0"

[dev-dependencies]
criterion = { version = "0.5.1", path = "c:\\Source\\oss\\criterion.rs\\" }

[[bench]]
name = "benchmark"
harness = false
